## Instalación de NumPy
Para la instalación es necesario recurrir a nuestra terminal y escribir el comando 
```
pip install numpy
```
***Nota: En Jupyter Notebook ya se encuentra instalado por defecto.***

In [2]:
import numpy as np

array = np.array([1,2,3,4,5])

print(array)

[1 2 3 4 5]


In [3]:
type(array)

numpy.ndarray

### Propiedades de los arrays

In [4]:
# Dimensión
array.ndim

1

In [5]:
# Elementos del array, elementos de la tupla
array.shape

(5,)

In [8]:
# Modificando el array
array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])

print(array.ndim)
print(array.shape)


2
(2, 5)


### Consulta el tipo de un array

In [9]:
# Tipo de variable que tiene un array
array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
print(array.dtype)

int32


In [11]:
# Flotante
array = np.array([[1,2,3,4,5],
                 [6,7,8,9.3,10]])
print(array.dtype)

float64


In [12]:
# Unicode
array = np.array(['Hola', 'que', 'tal'])
print(array.dtype)

<U4


### Arrays pregenerados
- **.zeros(*número*)** : DEVUELVE UN ARRAY DE UNA DIMENSIÓN FORMADO POR **N** CEROS
- **.zeros(*[tamaño_matriz]*)** : DEVUELVE UNA MATRIZ CON EL TAMAÑO ESPECIFICADO LLENA DE CEROS
De igual manera se puede hacer con números **uno**
- **.ones(*número*)** : DEVUELVE UN ARRAY DE UNA DIMENSIÓN FORMADO POR **N** UNOS
- **.ones(*[tamaño_matriz]*)** : DEVUELVE UNA MATRIZ CON EL TAMAÑO ESPECIFICADO LLENA DE UNOS

- **.eye(número)** : DEVUELVE LA MATRIZ CON LA DIAGONAL IDENTIDAD
Crear arrays a partir de un rango de valores
- **.arange(número)** : DEVUELVE UN ARRAY ENTERO DESDE ***0*** A ***número - 1***
- **.arange(número.)** : DEVUELVE UN ARRAY FLOTANTE DESDE ***0*** A ***número - 1***
- **.arange(n1, n2)** : DEVUELVE UN ARRAY ENTERO DESDE ***n1*** A ***n2 - 1***
- **.arange(n1, n2, salto)** : DEVUELVE UN ARRAY ENTERO DESDE ***n1*** A ***n2 - 1*** CADA ***salto*** NÚMEROS

In [14]:
array = np.arange(-10,11,2)
print(array)

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [15]:
array2 = np.arange(-20,21,4)
print(array2)

[-20 -16 -12  -8  -4   0   4   8  12  16  20]


### Operaciones con matrices
Para suma y resta deben tener las misma dimensiones


In [16]:
print(array + array2)

[-30 -24 -18 -12  -6   0   6  12  18  24  30]


In [18]:
print(array2 - array)

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


#### Multiplicar y/o dividir un array por algún número


In [19]:
print(array*2)

[-20 -16 -12  -8  -4   0   4   8  12  16  20]


In [20]:
print(array/2)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


#### Array recíproco

In [21]:
print(array ** -1.)

[-0.1        -0.125      -0.16666667 -0.25       -0.5                inf
  0.5         0.25        0.16666667  0.125       0.1       ]


C:\Users\26ald\AppData\Local\Temp\ipykernel_67444\3813850534.py:1: RuntimeWarning: divide by zero encountered in power
  print(array ** -1.)


### Índices
Los índices en **Numpy** funcionan exactamente igual que con listas. 

Las propiedades de slicing se conservan.

Los arrays son creados por referencia, ya que **numpy** genera cada dato de la forma mas óptima posible, es por eso que hay que tener cuidado al intentar modificar un array o subarray.
Para ahorrarnos este problema, los arrays tienen un método llamado ***.copy()** que hacer una copia por valor del array original.

### Arrays de mas dimensiones

In [22]:
arr_3d = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
cubo_de_unos = np.ones([3,3,3])
cubo_de_unos

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
# array 4d de unos
array4d = np.ones([3,3,3,3])

In [27]:
array4d

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

### Reshape y arange
El método **reshape** sirve para reformar las dimensiones y sus tamaños.

In [31]:
# Creación con RESHAPE
array = np.arange(9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
array = np.arange(1,28).reshape(3,3,3)
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

### Arrays transpuestos
filas --> columnas


columnas --> filas

In [40]:
prueba = np.arange(1,10).reshape(3,3)
prueba

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
prueba.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
prueba.T.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Swapaxes
Para cambiar valores de posición a posición

### Funciones adicionales
- **np.maximum(*arreglo*,*arreglo*)** : DEVUELVE EL ARRAY MÁXIMO
- **np.equal(*arreglo*,*arreglo*)** : DEVUELVE BOOLEAN SI SON IGUALES
- **np.greater(*arreglo*,*arreglo*)** : DEVUELVE UN ARRAY CON LOS VALORES *True* O *False* POR CADA ELEMENTO DEL PRIMERO ARRAY QUE SEA MAYOR AL DEL SEGUNDO ARRAY DE LA MISMA POSICIÓN
- **np.fabs(*arreglo*)** : DEVUELVE UN ARRAY CON EL VALOR ABS DE CADA ELEMENTO
- **np.ceil(*arreglo*)** : DEVUELVE EL ARRAY CON LOS ELEMENTOS REDONDEADOS A LA ALZA
- **np.floor(*arreglo*)** : DEVUELVE EL ARRAY CON LOS ELEMENTOS REDONDEADOS A LA BAJA

### Funciones aleatorias
- **np.random.rand()** : DEVUELVE UN NUMERO ALEATORIO ENTRE CERO Y UNO
- **np.random.rand(n)** : DEVUELVE UN ARRAY ALEATORIO CON ELEMENTOS ENTRE CERO Y UNO
- **np.random.rand(n1, n2)** : DEVUELVE UN ARRAY 2D ALEATORIO CON ELEMENTOS ENTRE CERO Y UNO


- **np.random.uniform(n, size=[d1,d2,d3...])** : DEVUELVE UNA MATRIZ CON NUMEROS DECIMALES DEL 0 AL N
- **np.random.uniform(n, size=[d1,d2,d3...])** : DEVUELVE UNA MATRIZ CON NUMEROS ENTEROS DE **N** A **M**


- **np.random.ranint(n, size=[d1,d2,d3...])** : DEVUELVE UNA MATRIZ CON NUMEROS ENTEROS DE **N** A **M**)**


- **np.random.normal(size=)** : DEVUELVE UN ARRAY CON CURVA GAUSSIANA


- **np.random.shuffle(array)** : CAMBIA DE POSICIÓN LOS VALORES INTERNOS ALEATORIAMENTE
- **np.random.permutation(n)** : DEVUELVE MATRIZ CON NUMERO ALEATORIOS EN UN RANGO *N*